import { Container, getContainer } from "@cloudflare/containers";

/**
 * content-factory — the M5 Worker fronting the whole A2A mesh.
 *
 *   hostname (prefix)                      → container
 *   content-factory.jackzhaojin.com        → coordinator (A2A + dashboard)
 *   content-factor-dash.jackzhaojin.com    → coordinator (Google-OAuth-registered dashboard host)
 *   content-factory-eval.jackzhaojin.com   → eval agent
 *   content-factory-gen.jackzhaojin.com    → content-gen agent
 *   content-factory-migrate.jackzhaojin.com → migration agent
 *   *.workers.dev                          → coordinator (fallback)
 *
 * Routing matches by SUBDOMAIN PREFIX (not full host) so the legacy *.xpri.ai
 * hostnames still route correctly while they remain in parallel. The xpri.ai
 * custom_domain routes (wrangler.jsonc) are pending manual infra teardown.
 *
 * The Worker also owns the D1 binding and exposes the secret-gated /d1/query
 * proxy that the containers' StoreDb d1-proxy driver calls back into (containers
 * get NO native bindings — references/cloudflare/d1-container, ~100ms/query).
 * Long SSE streams proxy straight through and block container sleep
 * (references/cloudflare/long-session-container: 22min streams, 0 drops).
 */

interface Env {
  COORDINATOR: DurableObjectNamespace<CoordinatorContainer>;
  EVAL: DurableObjectNamespace<EvalContainer>;
  CONTENT_GEN: DurableObjectNamespace<ContentGenContainer>;
  MIGRATION: DurableObjectNamespace<MigrationContainer>;
  DB: D1Database;
  // secrets
  D1_PROXY_SECRET: string;
  A2A_MESH_TOKEN: string;
  A2A_EDGE_TOKEN: string;
  R2_ACCESS_KEY_ID: string;
  R2_SECRET_ACCESS_KEY: string;
  AUTH_GOOGLE_ID: string;
  AUTH_GOOGLE_SECRET: string;
  AUTH_SECRET: string;
  MOONSHOT_API_KEY: string;
  CLAUDE_CODE_OAUTH_TOKEN: string;
  CLAUDE_ACCOUNT_UUID: string;
  CLAUDE_EMAIL: string;
  CLAUDE_ORG_UUID: string;
  // vars
  R2_BUCKET: string;
  R2_PUBLIC_BASE: string;
  R2_ACCOUNT_ID: string;
  AUTH_ALLOWED_EMAILS: string;
  MIGRATION_DEFAULT_BACKEND: string;
  DALIVE_MCP_URL: string;
}

const HOSTS = {
  coordinator: "https://content-factory.jackzhaojin.com",
  dash: "https://content-factor-dash.jackzhaojin.com",
  eval: "https://content-factory-eval.jackzhaojin.com",
  gen: "https://content-factory-gen.jackzhaojin.com",
  migrate: "https://content-factory-migrate.jackzhaojin.com",
} as const;

/** Env every agent container gets: store driver, mesh auth, R2. */
function commonEnv(env: Env): Record<string, string> {
  return {
    PORT: "8080",
    NODE_ENV: "production",
    D1_PROXY_URL: HOSTS.coordinator,
    D1_PROXY_SECRET: env.D1_PROXY_SECRET,
    A2A_MESH_TOKEN: env.A2A_MESH_TOKEN,
    A2A_EDGE_TOKEN: env.A2A_EDGE_TOKEN,
    R2_ACCESS_KEY_ID: env.R2_ACCESS_KEY_ID,
    R2_SECRET_ACCESS_KEY: env.R2_SECRET_ACCESS_KEY,
    R2_BUCKET: env.R2_BUCKET,
    R2_PUBLIC_BASE: env.R2_PUBLIC_BASE,
    R2_ACCOUNT_ID: env.R2_ACCOUNT_ID,
  };
}

export class CoordinatorContainer extends Container<Env> {
  defaultPort = 8080;
  sleepAfter = "30m"; // dashboard host — longer window so demo browsing stays warm
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.envVars = {
      ...commonEnv(env),
      A2A_PUBLIC_BASE: HOSTS.coordinator,
      EVAL_AGENT_URL: HOSTS.eval,
      CONTENT_GEN_URL: HOSTS.gen,
      MIGRATION_AGENT_URL: HOSTS.migrate,
      COORD_FANOUT_CONCURRENCY: "2",
      AUTH_GOOGLE_ID: env.AUTH_GOOGLE_ID,
      AUTH_GOOGLE_SECRET: env.AUTH_GOOGLE_SECRET,
      AUTH_SECRET: env.AUTH_SECRET,
      AUTH_ALLOWED_EMAILS: env.AUTH_ALLOWED_EMAILS,
    };
  }
}

export class EvalContainer extends Container<Env> {
  defaultPort = 8080;
  sleepAfter = "15m";
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.envVars = {
      ...commonEnv(env),
      A2A_PUBLIC_BASE: HOSTS.eval,
      EVAL_ENGINE: "real",
      // one eval at a time: 2 concurrent agentic evals (chromium + 4 Claude CLI
      // subprocesses each) killed the container even at standard-3 — and the
      // restart-rebuild then re-enqueued them into a crashloop
      EVAL_CONCURRENCY: "1",
      BROWSER_PERMITS: "2",
      CLAUDE_CODE_OAUTH_TOKEN: env.CLAUDE_CODE_OAUTH_TOKEN,
      // .claude.json oauthAccount stanza (generated by eval-entrypoint.sh) —
      // required for the CLI to use the OAuth token headlessly (v1 recipe)
      CLAUDE_ACCOUNT_UUID: env.CLAUDE_ACCOUNT_UUID,
      CLAUDE_EMAIL: env.CLAUDE_EMAIL,
      CLAUDE_ORG_UUID: env.CLAUDE_ORG_UUID,
    };
  }
}

export class ContentGenContainer extends Container<Env> {
  defaultPort = 8080;
  sleepAfter = "15m";
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.envVars = {
      ...commonEnv(env),
      A2A_PUBLIC_BASE: HOSTS.gen,
    };
  }
}

export class MigrationContainer extends Container<Env> {
  defaultPort = 8080;
  sleepAfter = "15m";
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.envVars = {
      ...commonEnv(env),
      A2A_PUBLIC_BASE: HOSTS.migrate,
      MIGRATION_CALLBACK_BASE: HOSTS.migrate,
      MIGRATION_DEFAULT_BACKEND: env.MIGRATION_DEFAULT_BACKEND,
      MOONSHOT_API_KEY: env.MOONSHOT_API_KEY,
      OPENCODE_BIN: "/root/.opencode/bin/opencode",
      PLAYWRIGHT_MCP_BIN: "/usr/local/bin/playwright-mcp",
      DALIVE_SKILLS_PATH: "/app/skills",
      DALIVE_MCP_URL: env.DALIVE_MCP_URL,
      OPENCODE_MIGRATION_TIMEOUT_MS: "1200000",
    };
  }
}

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json" } });

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    // ── /d1/query: the secret-gated D1 proxy the containers' StoreDb calls ──
    if (url.pathname === "/d1/query" && request.method === "POST") {
      if (request.headers.get("x-d1-secret") !== env.D1_PROXY_SECRET) {
        return json({ error: "forbidden" }, 403);
      }
      let payload: { sql?: string; params?: unknown[] };
      try {
        payload = await request.json();
      } catch {
        return json({ error: "bad json body" }, 400);
      }
      if (!payload.sql) return json({ error: "missing sql" }, 400);
      try {
        const result = await env.DB.prepare(payload.sql)
          .bind(...(payload.params ?? []))
          .all();
        return json({ success: result.success, results: result.results, meta: result.meta });
      } catch (e) {
        return json({ error: String((e as Error)?.message ?? e) }, 500);
      }
    }

    // ── /worker-health: the Worker itself, no container touch ──
    if (url.pathname === "/worker-health") {
      return json({ ok: true, worker: "content-factory", at: new Date().toISOString() });
    }

    // ── hostname → container (match by subdomain prefix so both *.xpri.ai and
    // *.jackzhaojin.com route correctly through the cutover) ──
    const host = url.hostname;
    const ns =
      host.startsWith("content-factory-eval.")
        ? env.EVAL
        : host.startsWith("content-factory-gen.")
          ? env.CONTENT_GEN
          : host.startsWith("content-factory-migrate.")
            ? env.MIGRATION
            : env.COORDINATOR; // content-factory / content-factor-dash / workers.dev fallback

    // Bot gate (cost): these are public hostnames — CT-log scanners hit them
    // every few minutes (measured: 3 req/4 min at 2am), which resets sleepAfter
    // and keeps containers awake 24/7. Agent surfaces only use known prefixes;
    // answer junk from the Worker so it never wakes a container. The
    // coordinator/dash hostname can't be path-gated (Next serves everything).
    if (ns !== env.COORDINATOR) {
      const p = url.pathname;
      const legit =
        p === "/a2a" ||
        p === "/health" ||
        p.startsWith("/.well-known/") ||
        p.startsWith("/hooks/") ||
        p.startsWith("/callbacks/") ||
        p.startsWith("/artifacts/") ||
        p.startsWith("/store/");
      if (!legit) return json({ error: "not found" }, 404);
    }

    return getContainer(ns, "singleton").fetch(request);
  },
};
